[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.23", features = [
  "json",
  "rustls",
], default-features = false }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
